name: July

zap:
  Compress: true
  MaxSize: 100
  FileName: "july-log.log"
  MaxBackup: 5
  LocalTime: true

jwt_secret: Rtg8BPKNEf2mB41gvKONGPZZQSaJWN2ijxR422Rgq0iBb5
tls:
  addr: :8081
  cert: conf/server.crt
  key: conf/server.key
port: 8080
mgo:
  database: "July"
  url: "mongodb://mongo1:27017,mongo2:27018,mongo3:27019/?replicaSet=rs0"
redis:
  cluster:
    - ":8001"
    - ":8002"
    - ":8003"
    - ":8004"
    - ":8005"
    - ":8006"
  docker_cluster:
      redis1: :8001
      redis2: :8002
      redis3: :8003
